# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e49a7249c2041d1fa0486444f8666f6a3c97f1bc2c52dfd7eef0033a55c91feafa2c3a27bf6086442197e1e3a896ee7f293fdaf56884830f0395c5bf159418d2

test:
  secret_key_base: 3ac9c421c3d2507cc02f30b7b0f45c8c1a3c5e23fdb12c0046b01737cc502efe4537c7684b8c240ab14402ca75bc9793a67b3cc262284a2d8fead3d5020f502a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
